version: '3'

services:

  front:
    image: safdarian/incognito-ood-frontend
    container_name: front
    ports:
      - "8080:8080"
    restart: on-failure
    networks:
      - ood_network
  
  nginx:
    image: nginx
    container_name: nginx
    ports: 
      - "8000:8000"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - worker1
      - worker2
    networks:
      - ood_network

  worker1:
    image: safdarian/incognito-ood-worker
    container_name: worker1
    restart: on-failure
    volumes:
      - ./csv_files:/csv_files
    command: ["uvicorn", "manager:app", "--host", "0.0.0.0", "--port", "8000"]
    networks:
      - ood_network

  worker2:
    image: safdarian/incognito-ood-worker
    container_name: worker2
    restart: on-failure
    volumes:
      - ./csv_files:/csv_files
    command: ["uvicorn", "manager:app", "--host", "0.0.0.0", "--port", "8000"]
    networks:
      - ood_network
  
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
    networks:
      - ood_network

networks:
  ood_network:
    name: ood_network
