version: '3'

services:

  front:
    image: safdarian/incognito-ood-frontend
    container_name: front
    ports:
      - 8080:8080
    restart: on-failure
  worker1:
    image: safdarian/incognito-ood-backend-worker
    container_name: worker1
    ports:
      - 8001:8000
    restart: on-failure
